require("data.prototypes.asteroids.Crude_Asteroid")
require("data.prototypes.asteroids.Sunrise_Sasparillaroid")
require("data.prototypes.asteroids.stone_processing")
require("data.prototypes.planets.nauvis")
require("data.prototypes.asteroids.Tech")